name: Example workflow for S3 Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [cortex-workflow]
    
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
        - uses: actions/checkout@v1

        - name: Deploy Static Content to S3
          run: |
            aws s3 sync . s3://tfs-idp-test-bucket/static-content --exclude ".git/*" --exclude ".github/*" --region ${{ secrets.AWS_DEFAULT_REGION }}
  
        - name: Invalidate CloudFront Cache
          run: |
            aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
